services:
  ui:
    image: "my-apache2:staging"
    ports:
      - '8080:80'
    restart: "on-failure"
  
  backend:
    image: "my-fastapi2:staging"
    environment:
      PORT: 8000
    ports:
      - '8081:8000'
    restart: "on-failure"